### ISSUE TITLE
Fix issue with last day in animation

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-VIZLAB/gw-conditions#47]
It _appears_ like the last day of the animation is showing data for October 2, 2021. Need to figure out what is going on:

![image](https://user-images.githubusercontent.com/13220910/147120681-893502b6-50fa-4a01-a1c3-0704cffb103c.png)

**Comment by ceenell** [comment]
As a temporary fix, the animation freezes on the first frame rather than the last now.

**Comment by lindsayplatt** [comment]
It was definitely an issue with timezones. I've got a fix and am building but this goes back to the historic data, too, so it is a bit big of a build (don't need to re-download, just re-average)!

**Comment by ceenell** [comment]
This is an issue again now that the data has been updated. Here's how where it freezes: 
![image](https://user-images.githubusercontent.com/17803537/148708916-bcd16378-ecf9-4314-ac1d-58acd821abbc.png)

I'm not sure why all the sites are turning orange at the end. This should be the same as the first day, because it rewinds, but it is not. And slightly before that, all of NJ turns orange while it is surrounded by blue.

The bar chart also is off on the last day. Maybe there are a bunch of NAs on that day for some reason, making the total % is less than 100?

**Comment by ceenell** [comment]
``` 
year21 <- read_csv('3_visualize/out/gw-conditions-year21.csv')

## sites by day
year21 %>%
  pivot_longer(contains('gwl_'), names_to = 'site', values_to = 'daily_obs') %>%
  filter(!is.na(daily_obs)) %>%
  group_by(day_seq) %>%
  summarize(sites = length(unique(site))) %>%
  arrange(sites) %>% arrange(sites)
```

Above produces this: 
![image](https://user-images.githubusercontent.com/17803537/148714987-cd2f535c-442b-4ced-a105-2d7a3daf4683.png)

So around 50% of sites are missing, and it thinks there are 366 days rather than 365

**Comment by lindsayplatt** [comment]
I think you are still seeing this because I've got the changes only on my fork still
