### ISSUE TITLE
Vue Error leading to the map not loading

### ISSUE THREAD

**Issue by jkreft-usgs** [USGS-VIZLAB/gw-conditions#71]
This is what I am seeing in the console...

```
GWL.vue?./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/@vue/cli-service/node_modules/vue-loader/lib??vue-loader-options:295 
        
       Uncaught (in promise) ReferenceError: i is not defined
    at VueComponent.callback (GWL.vue?./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/@vue/cli-service/node_modules/vue-loader/lib??vue-loader-options:295)
```

This happens a good chunk of the time on Edge and almost all the time on Firefox, which makes me think its a network race condition- but that's just a guess!

**Comment by lindsayplatt** [comment]
I have not been successful at recreating this issue on either Firefox or Edge yet. @hcorson-dosch is going to take a look at the Vue code

**Comment by lindsayplatt** [comment]
Hayley was still getting the error after #72 was merged but we spoke with Aaron and it was likely a symptom of the changes not making it up to prod due to Cloudfront caching being enabled on that bucket. On Friday, Hayley tested 10x on each of the browsers that _were_ failing and didn't have any issues, so it appears that the cloudfront cache lasting for 24 hours was about right. In the future, if we have a fix that needs to go to prod immediately, we will need to run a script to invalidate the cloudfront cache so that the changes are picked up. After testing many times (and with Aaron's help), the cloud

Should try to use `let` or `const` rather than `var` to set any variable (`let` is constrained to the current code block, while `var` can extend beyond and may sometimes creep into globals, so is more dangerous!).
